src/objects/Query__c.object
<CustomObject>
    <fields>
        <fullName>Query_Text__c</fullName>
        <label>Query Text</label>
        <type>TextArea</type>
    </fields>
    <label>Query</label>
    <nameField>
        <displayFormat>Q-{0000}</displayFormat>
        <label>Query Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reply_To__c.object
<CustomObject>
    <fields>
        <fullName>ContactCode__c</fullName>
        <label>ContactCode</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reply To</relationshipLabel>
        <relationshipName>Reply_To</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QueryCode__c</fullName>
        <label>QueryCode</label>
        <referenceTo>Query__c</referenceTo>
        <relationshipLabel>Reply To</relationshipLabel>
        <relationshipName>Reply_To</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Reply To</label>
    <nameField>
        <label>Reply To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reply To</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestEmailBatchResponse.cls
@isTest
private class TestEmailBatchResponse {
    static testMethod void testBatchOfReplyEmail() {
        List<Query__c> queryListInstance = new List<Query__c>();
        List<Reply_To__c> replyListInstance = new List<Reply_To__c>();
        List<Contact> contactListInstance = new List<Contact>();
        for(Integer i = 0; i < 5; i++) {
            Query__c queryInstance = new Query__c(Query_Text__c = 'query'+i);
            queryListInstance.add(queryInstance);
        }
        insert queryListInstance;
        
        List<Query__c> queryAssertListInstance = [SELECT Id, Query_Text__c
                                                  FROM Query__c
                                                  WHERE Query_Text__c LIKE 'query%'];
                                                 
        for(Integer i = 0; i < 5; i++) {
            Contact contactInstance = new Contact(LastName = 'TestLastName'+i);
            contactListInstance.add(contactInstance);
        }
        insert contactListInstance;
        
        List<Contact> contactAssertListInstance = [SELECT Id, LastName
                                                   FROM Contact
                                                   WHERE LastName LIKE 'Test%'];
                                                   
        for(Integer i = 0; i < 5; i++) {
            Reply_To__c replyTestInstance = new Reply_To__c(QueryCode__c = queryAssertListInstance[i].Id, ContactCode__c = contactAssertListInstance[i].Id);
            replyListInstance.add(replyTestInstance);
        }
        insert replyListInstance;
        
        EmailResponseBatch batchObj = new EmailResponseBatch();
        
        Test.startTest();
        Database.executeBatch(batchObj);
        Test.stopTest();
        
        System.assertequals(5,batchObj.mails.size());
    }
}