src/objects/Reply_To__c.object
<CustomObject>
    <fields>
        <fullName>ContactCode__c</fullName>
        <label>ContactCode</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reply To</relationshipLabel>
        <relationshipName>Reply_To</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>QueryCode__c</fullName>
        <label>QueryCode</label>
        <referenceTo>Query__c</referenceTo>
        <relationshipLabel>Reply To</relationshipLabel>
        <relationshipName>Reply_To</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Replied__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Replied</label>
        <type>Checkbox</type>
    </fields>
    <label>Reply To</label>
    <nameField>
        <label>Reply To Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Reply To</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EmailResponseBatch.cls
/***************************************************************************************************
 *  Title   : Batch Class to process the batch job of sending reply emails
 *  Class   : EmailResponseBatch
 *  Author  : Bhakti Gujarathi
***************************************************************************************************/

public with sharing class EmailResponseBatch implements Database.Batchable<sObject>{
    public List<Messaging.SingleEmailMessage> mails;
    //start method of batch to fetch the scopelist
    public Database.QueryLocator start(Database.BatchableContext batchCon) {
        return Database.getQueryLocator([SELECT Id, 
                                                Name,
                                                Replied__c,
                                                ContactCode__c,
                                                QueryCode__c
                                         FROM Reply_To__c
                                         WHERE CreatedDate = TODAY 
                                         AND Replied__c = false]);
    }
    
    //execute method to execute the actuall sending reply email job
    public void execute(Database.BatchableContext batchCon, List<Reply_To__c> replyToScopeList) {
         EmailTemplate emailTemplate = [SELECT Id, Body  
                                        FROM EmailTemplate 
                                        WHERE Name = 'Response Email'];
         mails = new List<Messaging.SingleEmailMessage>();
         //iterate over the scope list
         for(Reply_To__c  replyLoopInstance : replyToScopeList) {
              //create email instance
              Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
              //set the target who is supposed to recieve your email
              mail.setTargetObjectId(replyLoopInstance.ContactCode__c);
              //set the templateId to the VF Email Template
              mail.setTemplateId(emailTemplate.id);
              //set the object what is supposed to be sent in email
              mail.setWhatId(replyLoopInstance.QueryCode__c);
              replyLoopInstance.Replied__c = true;
              
              mails.add(mail);
         }
         //mail invocation
         update replyToScopeList; 
         Messaging.sendEmail(mails);
    }
    
    //finish method
    public void finish(Database.BatchableContext batchCon) {
        
    }
}