src/objects/Response_Item__c.object
<CustomObject>
    <fields>
        <fullName>For_Query__c</fullName>
        <label>For Query</label>
        <referenceTo>Query__c</referenceTo>
        <relationshipLabel>Response Items</relationshipLabel>
        <relationshipName>Response_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Response_Description__c</fullName>
        <label>Response Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Link__c</fullName>
        <label>Response Link</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Response_Title__c</fullName>
        <label>Response Title</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Response Item</label>
    <nameField>
        <displayFormat>RI-{00000}</displayFormat>
        <label>Response Item Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Response Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ResponseExtension.cls
public with sharing class ResponseExtension {
    public ApexPages.StandardController queri;
    public Id idOfParentQuery;
    public List<Response_Item__c> responseList;
    public ResponseExtension(apexPages.StandardController controller) {
        this.queri = controller;
        responseList = new List<Response_Item__c>();
    }
    
    public List<Response_Item__c> getresponseList() {
        idOfParentQuery = apexPages.currentPage().getParameters().get('queryId');
        responseList = [SELECT id,
                               Response_Title__c,
                               Response_Link__c,
                               Response_Description__c
                        FROM Response_Item__c
                        WHERE For_Query__c = :idOfParentQuery];
        return responseList;
    }
    //Save error: common.apex.runtime.bytecode.BytecodeApexObjectType cannot be cast to common.apex.runtime.impl.ApexType
    //https://developer.salesforce.com/forums/?id=906F0000000BQHgIAO
}